/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HomeRouteImport } from './routes/home'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OnlineIndexRouteImport } from './routes/online.index'
import { Route as OnlineCodeRouteImport } from './routes/online.$code'
import { Route as PlayComputerRouteImport } from './routes/play.computer'
import { Route as PlayLocalRouteImport } from './routes/play.local'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineIndexRoute = OnlineIndexRouteImport.update({
  id: '/online/',
  path: '/online/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineCodeRoute = OnlineCodeRouteImport.update({
  id: '/online/$code',
  path: '/online/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayComputerRoute = PlayComputerRouteImport.update({
  id: '/play/computer',
  path: '/play/computer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/play/local',
  path: '/play/local',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/setup': typeof SetupRoute
  '/online/$code': typeof OnlineCodeRoute
  '/play/computer': typeof PlayComputerRoute
  '/play/local': typeof PlayLocalRoute
  '/online/': typeof OnlineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/setup': typeof SetupRoute
  '/online/$code': typeof OnlineCodeRoute
  '/play/computer': typeof PlayComputerRoute
  '/play/local': typeof PlayLocalRoute
  '/online': typeof OnlineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/setup': typeof SetupRoute
  '/online/$code': typeof OnlineCodeRoute
  '/play/computer': typeof PlayComputerRoute
  '/play/local': typeof PlayLocalRoute
  '/online/': typeof OnlineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/home'
    | '/setup'
    | '/online/$code'
    | '/play/computer'
    | '/play/local'
    | '/online/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/home'
    | '/setup'
    | '/online/$code'
    | '/play/computer'
    | '/play/local'
    | '/online'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/home'
    | '/setup'
    | '/online/$code'
    | '/play/computer'
    | '/play/local'
    | '/online/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  HomeRoute: typeof HomeRoute
  SetupRoute: typeof SetupRoute
  OnlineCodeRoute: typeof OnlineCodeRoute
  PlayComputerRoute: typeof PlayComputerRoute
  PlayLocalRoute: typeof PlayLocalRoute
  OnlineIndexRoute: typeof OnlineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online/': {
      id: '/online/'
      path: '/online'
      fullPath: '/online/'
      preLoaderRoute: typeof OnlineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online/$code': {
      id: '/online/$code'
      path: '/online/$code'
      fullPath: '/online/$code'
      preLoaderRoute: typeof OnlineCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/computer': {
      id: '/play/computer'
      path: '/play/computer'
      fullPath: '/play/computer'
      preLoaderRoute: typeof PlayComputerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/local': {
      id: '/play/local'
      path: '/play/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  HomeRoute: HomeRoute,
  SetupRoute: SetupRoute,
  OnlineCodeRoute: OnlineCodeRoute,
  PlayComputerRoute: PlayComputerRoute,
  PlayLocalRoute: PlayLocalRoute,
  OnlineIndexRoute: OnlineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
